apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: c1
  region: us-west-2
nodeGroups:
  - name: ng1
    instanceType: t2.micro
    desiredCapacity: 2
  - name: ng2
    instanceType: t2.micro
    desiredCapacity: 1
   
